### ISSUE TITLE
Styling issues in quick settings

### ISSUE THREAD

**Issue by meybonomme** [andyholmes/gnome-shell-extension-valent#109]
### Current Behavior

As you can see from the first screenshot, everything is fine with the connected device and there are no stylistic issues. If there are no connected devices, the empty area is too large and there is too little margin on the bottom edge of the widget before the background apps line.

### Expected Behavior

If the devices are not connected, the style of the widget would also be fine.

### GNOME Version

Other (please specify)

### Other Version

Not dependent on GNOME version (tested with 45, 46 and 47)

### Operating System

Fedora 39, 40, 41

### Installed from

Nightly ZIP

### Version

1.alpha

### Screenshots

![Screenshot From 2024-11-01 07-03-38](https://github.com/user-attachments/assets/262d4a10-56a9-4590-b35d-0005223db22c)

![Screenshot From 2024-11-01 07-04-51](https://github.com/user-attachments/assets/06e8cb1e-8f73-4c6a-9a17-2f03d4b3cbdc)

**Comment by andyholmes** [comment]
Hi, I believe this is the expected result given GNOME Shell's style:

![Screenshot From 2024-11-01 12-01-59](https://github.com/user-attachments/assets/cd10f845-1296-42ca-959c-53948df808e8)

**Comment by meybonomme** [comment]
You're right. Sorry, I will close this issue, because it is from upstream.

**Comment by andyholmes** [comment]
No worries, I agree it's a bit odd. If it changes upstream I'll be happy to follow :)
