### ISSUE TITLE
Plans for GNOME 46 support?

### ISSUE THREAD

**Issue by meybonomme** [andyholmes/gnome-shell-extension-valent#94]
### Current Behavior

Doesn't work with GNOME 46.

### Expected Behavior

Valent is a great project and a very good replacement for the outdated GSConnect extension! Although this is an early development project, it works very well for the most part.

Since GNOME 46 was released a little over a month ago, are there any plans to add support for the Valent extension anytime soon?

### GNOME Version

Other (please specify)

### Other Version

46

### Operating System

Fedora 40

### Installed from

Other

### Version

1.alpha

**Comment by andyholmes** [comment]
Hi, support for GNOME 46 was added a little while ago:

https://github.com/andyholmes/gnome-shell-extension-valent/blob/c3ffbfd68393b0ba8f3537cda7a69f9bef310d2d/src/metadata.json.in#L7

**Comment by meybonomme** [comment]
Sorry, my bad... App will receive updates automatically via repository, but not the extension... 
I updated the extension manually and it works very well! Keep up the good work :+1:
