### ISSUE TITLE
Valent not compatible on Gnome shell 42.5 on Pop_OS!

### ISSUE THREAD

**Issue by agichim** [andyholmes/gnome-shell-extension-valent#95]
### Current Behavior

I installed it as a Gnome extension but simply can't enable as a message states it's not compatible.

### Expected Behavior

Well, it should be compatible with earlier version of Gnome.

### GNOME Version

Other (please specify)

### Other Version

42.5

### Operating System

Pop_OS! 22.04 LTS

### Installed from

GNOME Extensions

### Version

1.alpha

### Screenshots

![image](https://github.com/andyholmes/gnome-shell-extension-valent/assets/51931067/76219491-506d-45cd-81a7-765571423d84)

**Comment by andyholmes** [comment]
Hi!

I don't plan on maintaining support for older versions of GNOME, however if you or your distribution is interested in doing so, I do branch before each version bump.

Based on the last commit from the [`gnome-42` branch](https://github.com/andyholmes/gnome-shell-extension-valent/tree/gnome-42), I built this ZIP using the `/build-aux/misc/ego.sh` script (no guarantees):

[valent@andyholmes.ca.zip](https://github.com/andyholmes/gnome-shell-extension-valent/files/15133323/valent%40andyholmes.ca.zip)

**Comment by agichim** [comment]
Makes sense. Thanks for the branch link. I was just looking into why PopOS! didn't update Gnome and it's because by the end of the year they'll ditch Gnome and release their own DE. I won't be trying the branch I think, I'll stay with GSConnect for now, but so far when on latest Gnome versions been using Valent. I don't exactly know why, but just like it better than the other alternatives. Thanks.
