### ISSUE TITLE
Blank screen with cursor after screen goes blank

### ISSUE THREAD

**Issue by meybonomme** [andyholmes/gnome-shell-extension-valent#97]
### Current Behavior

When screen goes blank (screen turns off) and I will wake screen up with moving cursor or key press, I have black screen with cursor and desktop won't appearing any more. The only solution is to put the computer to sleep and wake it up again. If I wait longer and the screen locks, this problem does not exist.

The problem only occurs with the Valent extension and I disabled all other extensions for testing. If the Valent extension is disabled, this problem does not occur. 

The problem occurs with both GNOME 45 (the older version of the extension) and GNOME 46 (the latest version of the extension).

### Expected Behavior

The desktop appears as expected.

### GNOME Version

Other (please specify)

### Other Version

45, 46

### Operating System

Fedora 39, Fedora 40

### Installed from

Nightly ZIP

### Version

1.alpha

**Comment by andyholmes** [comment]
I've noticed this too, but didn't realize it was the extension causing it.

Does this happen consistently for you, or are their special cases necessary to reproduce it you know of? I've definitely noticed this, but just tried with a 1min timeout and it did not occur.

Is it possible this has some relation to a screen blank -> suspend cycle?

**Comment by andyholmes** [comment]
If you want to give the [test ZIP from #98](https://github.com/andyholmes/gnome-shell-extension-valent/actions/runs/8854345003) a shot, I think just dropping the session override should fix it.

I don't see that anything else could be causing this, and it doesn't seem necessary/effective anymore anyways.

**Comment by meybonomme** [comment]
I think you should remove some link for session.js, because with test ZIP I got error when activating extension:

 `ImportError: Unable to load file from: file:///home/meybo/.local/share/gnome-shell/extensions/valent@andyholmes.ca/session.js (Error opening file /home/meybo/.local/share/gnome-shell/extensions/valent@andyholmes.ca/session.js: No such file or directory)`

**Comment by meybonomme** [comment]
From extension.js:

`import * as Session from './session.js';`

But if I remove this row, I got next error:

`ReferenceError: Session is not defined`

**Comment by meybonomme** [comment]
Figured out - you should remove following lines from extension.js:

Line 7:
`import * as Session from './session.js';`

Line 14:
`Session.enable();`

Line 30:
`Session.disable();`

**Comment by andyholmes** [comment]
Awesome, thanks very much for the testing! I'll set the PR to merge with those updates, and see if I can cherr-pick the change for the `gnome-45` branch.

**Comment by meybonomme** [comment]
I did repeated tests, the extension works and this annoying problem is now gone :+1:
